/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_vistaverde;

/**
 *
 * @author andre_8v8gtn3
 */
public class Configurar_Cuota extends javax.swing.JFrame {
    
    private Condominio condominio;

public Configurar_Cuota(Condominio condominio) {
    initComponents();
    this.condominio = condominio;
    
    lblCuotaActual.setText("Q " + String.format("%.2f", condominio.getCuota()));
lblTotalEsperado.setText("Q " + String.format("%.2f", condominio.getTotalEsperado()));
lblMensaje.setText("");
}

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Configurar_Cuota.class.getName());

    /**
     * Creates new form Configurar_Cuota
     */
    public Configurar_Cuota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCuotaActual = new javax.swing.JLabel();
        lblTotalEsperado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNuevaCuota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cuota Actual");

        jLabel2.setText("Total esperado / Anual");

        lblCuotaActual.setText(" ");

        lblTotalEsperado.setText(" ");

        jLabel6.setText("Nueva Cuota (Q)");

        jLabel7.setText("* Aplica a pagos registrados de ahora en adelante");

        jLabel8.setText("Modificación de Cuota");

        btnActualizar.setText("Actualizar Cuota");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        lblMensaje.setText(" ");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNuevaCuota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCuotaActual)
                                    .addComponent(lblTotalEsperado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCuotaActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalEsperado))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNuevaCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    try {
    String textoNuevaCuota = txtNuevaCuota.getText().trim();
    if (textoNuevaCuota.isEmpty()) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "Ingrese el nuevo monto de la cuota.");
        txtNuevaCuota.requestFocus();
        return;
    }

    if (!textoNuevaCuota.matches("[0-9]+(\\.[0-9]{1,2})?")) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "Ingrese un monto válido. Ejemplo: 1500 o 1500.00");
        txtNuevaCuota.requestFocus();
        return;
    }

    double nuevaCuota = Double.parseDouble(textoNuevaCuota);


    if (nuevaCuota <= 0) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "La cuota debe ser mayor a Q0.00");
        txtNuevaCuota.requestFocus();
        return;
    }


    if (nuevaCuota == condominio.getCuota()) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "La nueva cuota es igual a la actual. Ingrese un monto diferente.");
        txtNuevaCuota.requestFocus();
        return;
    }


    if (nuevaCuota > 50000) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "El monto ingresado es demasiado alto. Verifique el valor.");
        txtNuevaCuota.requestFocus();
        return;
    }


    condominio.setCuota(nuevaCuota);
    Persistencia.guardar(condominio);


    lblCuotaActual.setText("Q " + String.format("%.2f", condominio.getCuota()));
    lblTotalEsperado.setText("Q " + String.format("%.2f", condominio.getTotalEsperado()));

    ManejadorErrores.mostrarExito(lblMensaje, 
        "Cuota actualizada correctamente a Q" + String.format("%.2f", nuevaCuota) 
        + ". Total esperado: Q" + String.format("%.2f", condominio.getTotalEsperado()));
    limpiarCampos();

} catch (NumberFormatException e) {
    ManejadorErrores.registrar(e, "Configurar_Cuota - btnActualizar - NumberFormat");
    ManejadorErrores.mostrarMensaje(lblMensaje, "El monto ingresado no es un número válido.");
} catch (Exception e) {
    ManejadorErrores.registrar(e, "Configurar_Cuota - btnActualizar");
    ManejadorErrores.mostrarMensaje(lblMensaje, "Error inesperado. Intente de nuevo.");
}
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiarCampos();
lblMensaje.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Configurar_Cuota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCuotaActual;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTotalEsperado;
    private javax.swing.JTextField txtNuevaCuota;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
    txtNuevaCuota.setText("");
    txtNuevaCuota.requestFocus();
}

}
