/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_vistaverde;

/**
 *
 * @author andre_8v8gtn3
 */
public class Estado_de_Cuenta extends javax.swing.JFrame {
    private Condominio condominio;

public Estado_de_Cuenta(Condominio condominio) {
    initComponents();
    this.condominio = condominio;
    
for (int i = 1; i <= 30; i++) {
    cmbCasa.addItem(String.valueOf(i));
}

lblPropietario.setText("-");
lblTotalPagado.setText("Q 0.00");
lblMensaje.setText("");
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Estado_de_Cuenta.class.getName());

    /**
     * Creates new form Estado_de_Cuenta
     */
    public Estado_de_Cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCasa = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPagados = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPendientes = new javax.swing.JList<>();
        lblTotalPagado = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        jLabel1.setText("Meses Pagados");

        jLabel2.setText("Meses Pendientes");

        jLabel3.setText("Total Pagado:");

        jLabel4.setText("Casa");

        jLabel5.setText("Propietario:");

        jScrollPane3.setViewportView(listPagados);

        jScrollPane4.setViewportView(listPendientes);

        lblTotalPagado.setText(" ");

        lblMensaje.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnConsultar))
                                    .addComponent(lblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(91, 91, 91))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(8, 8, 8)
                                                .addComponent(lblTotalPagado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblTotalPagado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    try {

    if (cmbCasa.getSelectedItem() == null) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "Seleccione un número de casa.");
        return;
    }

    int  casa    = Integer.parseInt(cmbCasa.getSelectedItem().toString());
    Casa c       = condominio.getCasa(casa);

    if (c == null) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "La casa seleccionada no existe.");
        return;
    }

    if (!c.tienePropietario()) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "La Casa " + casa + " no tiene propietario registrado.");
        lblPropietario.setText("-");
        lblTotalPagado.setText("Q 0.00");
        listPagados.setModel(new javax.swing.DefaultListModel<>());
        listPendientes.setModel(new javax.swing.DefaultListModel<>());
        return;
    }


    lblPropietario.setText(c.getPropietario().getNombreCompleto());


    String[] nombreMeses = {
        "Enero","Febrero","Marzo","Abril","Mayo","Junio",
        "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
    };

    javax.swing.DefaultListModel<String> modeloPagados = new javax.swing.DefaultListModel<>();
    for (Pago p : c.getPagos()) {
        modeloPagados.addElement(nombreMeses[p.getMes() - 1] + " " + p.getAnio() 
            + " - Q" + String.format("%.2f", p.getMonto()));
    }
    listPagados.setModel(modeloPagados);

    int anioActual = java.time.LocalDate.now().getYear();
    int mesActual  = java.time.LocalDate.now().getMonthValue();

    javax.swing.DefaultListModel<String> modeloPendientes = new javax.swing.DefaultListModel<>();
    for (int m : c.getMesesPendientes(anioActual, mesActual)) {
        modeloPendientes.addElement(nombreMeses[m - 1] + " " + anioActual);
    }
    listPendientes.setModel(modeloPendientes);

    lblTotalPagado.setText("Q " + String.format("%.2f", c.getTotalPagado()));


    if (modeloPendientes.isEmpty()) {
        ManejadorErrores.mostrarExito(lblMensaje, 
            "La Casa " + casa + " está al día con todos sus pagos.");
    } else {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "La Casa " + casa + " tiene " + modeloPendientes.size() + " mes(es) pendiente(s).");
    }

} catch (NumberFormatException e) {
    ManejadorErrores.registrar(e, "Estado_de_Cuenta - btnConsultar - NumberFormat");
    ManejadorErrores.mostrarMensaje(lblMensaje, "Error en el número de casa. Intente de nuevo.");
} catch (Exception e) {
    ManejadorErrores.registrar(e, "Estado_de_Cuenta - btnConsultar");
    ManejadorErrores.mostrarMensaje(lblMensaje, "Error inesperado. Intente de nuevo.");
}
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Estado_de_Cuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cmbCasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTotalPagado;
    private javax.swing.JList<String> listPagados;
    private javax.swing.JList<String> listPendientes;
    // End of variables declaration//GEN-END:variables
}
