/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_vistaverde;

/**
 *
 * @author andre_8v8gtn3
 */
public class Registro_Pago extends javax.swing.JFrame {
    private Condominio condominio;

public Registro_Pago(Condominio condominio) {
    initComponents();
    this.condominio = condominio;
    

for (int i = 1; i <= 30; i++) {
    cmbCasa.addItem(String.valueOf(i));
}

String[] meses = {
    "Enero","Febrero","Marzo","Abril","Mayo","Junio",
    "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
};
for (String mes : meses) {
    cmbMes.addItem(mes);
}

int anioActual = java.time.LocalDate.now().getYear();
cmbAnio.addItem(String.valueOf(anioActual - 1));
cmbAnio.addItem(String.valueOf(anioActual));
cmbAnio.addItem(String.valueOf(anioActual + 1));
cmbAnio.setSelectedItem(String.valueOf(anioActual));

cmbMes.setSelectedIndex(java.time.LocalDate.now().getMonthValue() - 1);

lblMonto.setText("Q " + String.format("%.2f", condominio.getCuota()));

lblPropietario.setText("Sin propietario");
lblMensaje.setText("");
    
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_Pago.class.getName());

    /**
     * Creates new form Registro_Pago
     */
    public Registro_Pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCasa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbAnio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de Casa");

        cmbCasa.addActionListener(this::cmbCasaActionPerformed);

        jLabel2.setText("Propietario");

        lblPropietario.setText(" ");

        jLabel4.setText("Mes");

        jLabel5.setText("Año");

        jLabel6.setText("Monto (cuota oficial)");

        lblMonto.setText(" ");

        btnRegistrar.setText("Registrar Pago");
        btnRegistrar.setActionCommand("Registrar Pagp");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiarCampos();
lblMensaje.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
try {

    if (cmbCasa.getSelectedItem() == null) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "Seleccione un número de casa.");
        return;
    }
    if (cmbMes.getSelectedItem() == null) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "Seleccione un mes.");
        return;
    }
    if (cmbAnio.getSelectedItem() == null) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "Seleccione un año.");
        return;
    }

    int    casa  = Integer.parseInt(cmbCasa.getSelectedItem().toString());
    int    mes   = cmbMes.getSelectedIndex() + 1;
    int    anio  = Integer.parseInt(cmbAnio.getSelectedItem().toString());
    double monto = condominio.getCuota();

    if (condominio.getCasa(casa) == null) {
        ManejadorErrores.mostrarMensaje(lblMensaje, "La Casa " + casa + " no existe en el sistema.");
        return;
    }

    if (!condominio.getCasa(casa).tienePropietario()) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "La Casa " + casa + " no tiene propietario. Regístrelo primero en 'Registrar Propietario'.");
        return;
    }

    if (monto <= 0) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "El monto de la cuota no es válido. Verifique la configuración.");
        return;
    }

    if (condominio.getCasa(casa).existePago(mes, anio)) {
        ManejadorErrores.mostrarMensaje(lblMensaje, 
            "La Casa " + casa + " ya tiene registrado el pago de "
            + cmbMes.getSelectedItem() + " " + anio + ". No se permiten pagos duplicados.");
        return;
    }

    String[] nombreMeses = {
        "Enero","Febrero","Marzo","Abril","Mayo","Junio",
        "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
    };
    for (int m = 1; m < mes; m++) {
        if (!condominio.getCasa(casa).existePago(m, anio)) {
            ManejadorErrores.mostrarMensaje(lblMensaje,
                "No puede pagar " + nombreMeses[mes - 1] + " " + anio 
                + " porque tiene pendiente " + nombreMeses[m - 1] + " " + anio + ".");
            return;
        }
    }

    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
    this,
    "¿Confirma registrar el siguiente pago?\n\n"
    + "Casa: " + casa + "\n"
    + "Propietario: " + condominio.getCasa(casa).getPropietario().getNombreCompleto() + "\n"
    + "Mes: " + cmbMes.getSelectedItem() + " " + anio + "\n"
    + "Monto: Q" + String.format("%.2f", monto),
    "Confirmar Pago",
    javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
    ManejadorErrores.mostrarMensaje(lblMensaje, "Registro cancelado.");
    return;
}
    boolean ok = condominio.registrarPago(casa, mes, anio, monto);
if (ok) {
    Persistencia.guardar(condominio);
    
    // Enviar correo al propietario
    String correoDestinatario = condominio.getCasa(casa).getPropietario().getCorreoElectronico();
    String nombrePropietario  = condominio.getCasa(casa).getPropietario().getNombreCompleto();
    String nombreMes          = cmbMes.getSelectedItem().toString();
    
    boolean correoEnviado = EnvioCorreo.enviarComprobante(
        correoDestinatario,
        nombrePropietario,
        casa,
        nombreMes,
        anio,
        monto
    );
    
    if (correoEnviado) {
        ManejadorErrores.mostrarExito(lblMensaje,
            "Pago registrado: Casa " + casa + " | "
            + cmbMes.getSelectedItem() + " " + anio
            + " | Q" + String.format("%.2f", monto)
            + " | Comprobante enviado a: " + correoDestinatario);
    } else {
        ManejadorErrores.mostrarExito(lblMensaje,
            "Pago registrado: Casa " + casa + " | "
            + cmbMes.getSelectedItem() + " " + anio
            + " | Q" + String.format("%.2f", monto)
            + " | (No se pudo enviar el correo)");
    }
    limpiarCampos();
}

} catch (NumberFormatException e) {
    ManejadorErrores.registrar(e, "Registro_Pago - btnRegistrar - NumberFormat");
    ManejadorErrores.mostrarMensaje(lblMensaje, "Error en los datos ingresados. Verifique casa y año.");
} catch (Exception e) {
    ManejadorErrores.registrar(e, "Registro_Pago - btnRegistrar");
    ManejadorErrores.mostrarMensaje(lblMensaje, "Error inesperado. Intente de nuevo.");
}



    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCasaActionPerformed
    int casa = Integer.parseInt(cmbCasa.getSelectedItem().toString());
if (condominio.getCasa(casa).tienePropietario()) {
    lblPropietario.setText(condominio.getCasa(casa).getPropietario().getNombreCompleto());
} else {
    lblPropietario.setText("Sin propietario registrado");
}
lblMonto.setText("Q " + String.format("%.2f", condominio.getCuota()));
    }//GEN-LAST:event_cmbCasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro_Pago().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox<String> cmbCasa;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblPropietario;
    // End of variables declaration//GEN-END:variables

private void limpiarCampos() {
    cmbCasa.setSelectedIndex(0);
    cmbMes.setSelectedIndex(java.time.LocalDate.now().getMonthValue() - 1);
    cmbAnio.setSelectedItem(String.valueOf(java.time.LocalDate.now().getYear()));
    lblPropietario.setText("Sin propietario");
    lblMonto.setText("Q " + String.format("%.2f", condominio.getCuota()));
}

}
