/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_vistaverde;

/**
 *
 * @author andre_8v8gtn3
 */
public class Reporte_General extends javax.swing.JFrame {
    private Condominio condominio;

public Reporte_General(Condominio condominio) {
    initComponents();
    this.condominio = condominio;
    
    lblMensaje.setText("");
cargarReporte();
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reporte_General.class.getName());

    /**
     * Creates new form Reporte_General
     */
    public Reporte_General() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotalRecaudado = new javax.swing.JLabel();
        lblTotalEsperado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFaltante = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        jLabel1.setText("Total Recaudado: ");

        lblTotalRecaudado.setText(" ");

        lblTotalEsperado.setText(" ");

        jLabel2.setText("Total Esperado: ");

        lblFaltante.setText(" ");

        jLabel3.setText("Faltante:");

        btnActualizar.setText("Actualizar Información");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        lblMensaje.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(btnActualizar)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalRecaudado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalEsperado)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFaltante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    cargarReporte();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reporte_General().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFaltante;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTotalEsperado;
    private javax.swing.JLabel lblTotalRecaudado;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables

private void cargarReporte() {
    try {
        int mes  = java.time.LocalDate.now().getMonthValue();
        int anio = java.time.LocalDate.now().getYear();

        String[] nombreMeses = {
            "Enero","Febrero","Marzo","Abril","Mayo","Junio",
            "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
        };

        String[] columnas = {
            "Casa", "Propietario", "Estado " + nombreMeses[mes - 1], "Total Año"
        };

        Object[][] filas = new Object[Condominio.TOTAL_CASAS][4];

        for (int i = 0; i < Condominio.TOTAL_CASAS; i++) {
            Casa c = condominio.getCasa(i + 1);

            filas[i][0] = "Casa " + c.getNumeroCasa();

            filas[i][1] = c.tienePropietario()
                ? c.getPropietario().getNombreCompleto()
                : "Sin propietario";

            filas[i][2] = c.existePago(mes, anio) ? "Pagado" : "Pendiente";

            filas[i][3] = "Q " + String.format("%.2f", c.getTotalPagadoAnio(anio));
        }
        tblReporte.setModel(new javax.swing.table.DefaultTableModel(filas, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        double totalRecaudado = condominio.getTotalRecaudadoMes(mes, anio);
        double totalEsperado  = condominio.getTotalEsperado();
        double faltante       = totalEsperado - totalRecaudado;

        lblTotalRecaudado.setText("Q " + String.format("%.2f", totalRecaudado));
        lblTotalEsperado.setText("Q "  + String.format("%.2f", totalEsperado));

        if (faltante > 0) {
            lblFaltante.setForeground(java.awt.Color.RED);
            lblFaltante.setText("Q " + String.format("%.2f", faltante));
        } else {
            lblFaltante.setForeground(new java.awt.Color(0, 130, 0));
            lblFaltante.setText("Q 0.00 - Recaudación completa");
        }

        ManejadorErrores.mostrarExito(lblMensaje,
            "Reporte de " + nombreMeses[mes - 1] + " " + anio + " cargado correctamente.");

    } catch (Exception e) {
        ManejadorErrores.registrar(e, "Reporte_General - cargarReporte");
        ManejadorErrores.mostrarMensaje(lblMensaje, "Error al cargar el reporte. Intente de nuevo.");
    }
}

}
