/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_vistaverde;

import java.awt.HeadlessException;
import java.io.IOException;

/**
 *
 * @author andre_8v8gtn3
 */
public class Reporte_General extends javax.swing.JFrame {
    private Condominio condominio;

public Reporte_General(Condominio condominio) {
    initComponents();
    this.condominio = condominio;

    // PRIMERO llenar los combos
    String[] meses = {
        "Enero","Febrero","Marzo","Abril","Mayo","Junio",
        "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
    };
    for (String mes : meses) {
        cmbMes.addItem(mes);
    }

    int anioActual = java.time.LocalDate.now().getYear();
    cmbAnio.addItem(String.valueOf(anioActual - 1));
    cmbAnio.addItem(String.valueOf(anioActual));
    cmbAnio.addItem(String.valueOf(anioActual + 1));

    cmbMes.setSelectedIndex(java.time.LocalDate.now().getMonthValue() - 1);
    cmbAnio.setSelectedItem(String.valueOf(anioActual));

    lblMensaje.setText("");


    cargarReporte();
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reporte_General.class.getName());

    /**
     * Creates new form Reporte_General
     */
    public Reporte_General() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        btnCerrar1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTotalRecaudado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalEsperado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFaltante = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAnio = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        btnActualizar.setText("Actualizar Información");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        lblMensaje.setText(" ");

        btnExportar.setText("Exportar TXT");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte2.png"))); // NOI18N

        lblNombre2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombre2.setText("Reporte General");

        btnCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar1.jpg"))); // NOI18N
        btnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar1.addActionListener(this::btnCerrar1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(218, 235, 235));

        lblTotalRecaudado.setText(" ");

        jLabel1.setText("Total Recaudado: ");

        jLabel2.setText("Total Esperado: ");

        lblTotalEsperado.setText(" ");

        jLabel3.setText("Faltante:");

        lblFaltante.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalRecaudado)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalEsperado))
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFaltante)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel4.setText("Mes a consultar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExportar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar))
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    cargarReporte();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed

    try {
    int mes  = cmbMes.getSelectedIndex() + 1;
    int anio = Integer.parseInt(cmbAnio.getSelectedItem().toString());

    String[] nombreMeses = {
        "Enero","Febrero","Marzo","Abril","Mayo","Junio",
        "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
    };

    // Elegir donde guardar el archivo
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte");
    fileChooser.setSelectedFile(new java.io.File(
        "Reporte_VistaVerde_" + nombreMeses[mes - 1] + "_" + anio + ".txt"
    ));

    int opcion = fileChooser.showSaveDialog(this);
    if (opcion != javax.swing.JFileChooser.APPROVE_OPTION) return;

    java.io.File archivo = fileChooser.getSelectedFile();

    // Escribir el reporte
    try (java.io.PrintWriter pw = new java.io.PrintWriter(
            new java.io.FileWriter(archivo))) {

        pw.println("================================================");
        pw.println("   REPORTE GENERAL - CONDOMINIO VISTA VERDE     ");
        pw.println("   " + nombreMeses[mes - 1] + " " + anio);
        pw.println("================================================");
        pw.println();
        pw.printf("%-10s %-30s %-12s %-15s%n",
            "Casa", "Propietario", "Estado", "Total Año");
        pw.println("------------------------------------------------");

        for (Casa c : condominio.getCasas()) {
            String propietario = c.tienePropietario()
                ? c.getPropietario().getNombreCompleto()
                : "Sin propietario";
            String estado = c.existePago(mes, anio) ? "Pagado" : "Pendiente";
            double totalAnio = c.getTotalPagadoAnio(anio);

            pw.printf("%-10s %-30s %-12s Q%-14.2f%n",
                "Casa " + c.getNumeroCasa(),
                propietario,
                estado,
                totalAnio
            );
        }

        pw.println("------------------------------------------------");
        pw.println();

        double recaudado = condominio.getTotalRecaudadoMes(mes, anio);
        double esperado  = condominio.getTotalEsperado();
        double faltante  = esperado - recaudado;

        pw.printf("Total recaudado este mes : Q%.2f%n", recaudado);
        pw.printf("Total esperado este mes  : Q%.2f%n", esperado);
        pw.printf("Faltante                 : Q%.2f%n", faltante);
        pw.println();
        pw.println("================================================");
        pw.println("Generado por Sistema Vista Verde - " + 
            java.time.LocalDate.now());
        pw.println("================================================");
    }   catch (IOException ex) {
            System.getLogger(Reporte_General.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    ManejadorErrores.mostrarExito(lblMensaje,
        "Reporte exportado correctamente en: " + archivo.getAbsolutePath());

} catch (HeadlessException e) {
    ManejadorErrores.registrar(e, "Reporte_General - btnExportar");
    ManejadorErrores.mostrarMensaje(lblMensaje, "Error al exportar el reporte. Intente de nuevo.");
}  
        
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reporte_General().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnExportar;
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFaltante;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTotalEsperado;
    private javax.swing.JLabel lblTotalRecaudado;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables

private void cargarReporte() {
    try {
        
        if (cmbMes.getSelectedItem() == null || cmbAnio.getSelectedItem() == null) {
            return;
        }
        int mes  = cmbMes.getSelectedIndex() + 1;
        int anio = Integer.parseInt(cmbAnio.getSelectedItem().toString());

        String[] nombreMeses = {
            "Enero","Febrero","Marzo","Abril","Mayo","Junio",
            "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
        };

        // Columnas
        String[] columnas = {
            "Casa", "Propietario", "Estado " + nombreMeses[mes - 1], "Total Año"
        };

        // Filas
        Object[][] filas = new Object[Condominio.TOTAL_CASAS][4];
        for (int i = 0; i < Condominio.TOTAL_CASAS; i++) {
            Casa c = condominio.getCasa(i + 1);
            filas[i][0] = "Casa " + c.getNumeroCasa();
            filas[i][1] = c.tienePropietario()
                ? c.getPropietario().getNombreCompleto()
                : "Sin propietario";
            String estado;
                if (!c.tienePropietario()) {
                    estado = "Sin propietario";
} else {
    int mesReg  = c.getPropietario().getMesRegistro();
    int anioReg = c.getPropietario().getAnioRegistro();

    if (anio < anioReg || (anio == anioReg && mes < mesReg)) {
        estado = "No aplica";
    } else {
        estado = c.existePago(mes, anio) ? "Pagado" : "Pendiente";
    }
}

            filas[i][2] = estado;
            filas[i][3] = "Q " + String.format("%.2f", c.getTotalPagadoAnio(anio));
        }

        // Cargar tabla
        tblReporte.setModel(new javax.swing.table.DefaultTableModel(filas, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        // Totales
        double recaudado = condominio.getTotalRecaudadoMes(mes, anio);
        double esperado  = condominio.getTotalEsperado();
        double faltante  = esperado - recaudado;

        lblTotalRecaudado.setText("Q " + String.format("%.2f", recaudado));
        lblTotalEsperado.setText("Q "  + String.format("%.2f", esperado));

        if (faltante > 0) {
            lblFaltante.setForeground(java.awt.Color.RED);
            lblFaltante.setText("Q " + String.format("%.2f", faltante));
        } else {
            lblFaltante.setForeground(new java.awt.Color(0, 130, 0));
            lblFaltante.setText("Q 0.00 - Recaudacion completa");
        }

        ManejadorErrores.mostrarExito(lblMensaje,
            "Reporte de " + nombreMeses[mes - 1] + " " + anio + " cargado correctamente.");

    } catch (NumberFormatException e) {
        ManejadorErrores.registrar(e, "Reporte_General - cargarReporte");
        ManejadorErrores.mostrarMensaje(lblMensaje, "Error al cargar el reporte. Intente de nuevo.");
    }
}

}
